config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'home/index'

  get 'contacts' => 'pages#contacts'
  get 'about' => 'pages#about'
  get 'support' => 'pages#support'
  get 'docs' => 'pages#docs'
  

  resources :products
  resources :events
  resources :directions do
    resources :examples
  end

  #resources :examples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord

  has_many :examples

end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/example.rb
class Example < ApplicationRecord

  belongs_to :direction

end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController

 
 before_filter only: [:new, :create]

  def index
    @directions = Direction.all
  end

  def show
    @direction = Direction.find(params[:id])
  end

  def new
  end

  def create
    @direction = Direction.new(direction_params)
    
    if @direction.save
      redirect_to new_direction_path
    else
      render action: 'new'
    end
  end

  def edit
    @direction = Direction.find(params[:id])
  end

  def update
    @direction = Direction.find(params[:id])

    if @direction.update(direction_params)
      redirect_to new_direction_path
    else
      render action: 'edit'
    end    
  end

  def destroy
    @direction = Direction.find(params[:id])
    @direction.destroy

    redirect_to directions_path
  end

  private

  def direction_params
    params.require(:direction).permit(:title, :content, :thumbnail)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

 
 before_filter only: [:new, :create]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
  end

  def create
    @event = Event.new(event_params)
    
    if @event.save
      redirect_to new_event_path
    else
      render action: 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to new_event_path
    else
      render action: 'edit'
    end    
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :content, :date, :thumbnail)
  end

end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  
  
  def create
    @direction = Direction.find(params[:direction_id])
    @direction.examples.create(example_params)

    redirect_to direction_path(@direction)
  end

  private

  def example_params
    params.require(:example).permit(:title, :content)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  @directions = Direction.all
  @events = Event.last(5)
  @products = Product.last(6).reverse
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contacts
  end

  def about
  end

  def docs
  end

  def csupport
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

before_filter only: [:new, :create]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
  end

  def create
    @product = Product.new(product_params)
    
    if @product.save
      redirect_to new_product_path
    else
      render action: 'new'
    end
  end

  def edit
    @product = product.find(params[:id])
  end

  def update
    @product = product.find(params[:id])

    if @product.update(product_params)
      redirect_to new_product_path
    else
      render action: 'edit'
    end    
  end

  def destroy
    @product = product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :content, :thumbnail)
  end

end

app/helpers/Products_helper.rb
module ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def nav_link(link_text, link_path)
  class_name = current_page?(link_path) ? 'active' : ''

  content_tag(:li, :class => class_name) do
    link_to link_text, link_path
  end
end

end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/directions/index.html.erb
<div class="container">

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

	<% @directions.each_with_index do |direction, n| %>

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading<%= "#{n}" %>">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= "#{n}" %>" aria-expanded="<%= n==0 ? 'true' : 'false' %>" aria-controls="collapse<%= "#{n}" %>">


          <%= direction.title %>
        </a>
      </h4>
    </div>
    <div id="collapse<%= "#{n}" %>" class="panel-collapse collapse <%= n==0 ? 'in' : '' %>" role="tabpanel" aria-labelledby="heading<%= "#{n}" %>">
      <div class="panel-body">
        
		<% direction.examples.each do |example| %>
		<p>
		<%= link_to "#{example.title}".html_safe,example.content %>	
		</p>
		<% end %>

      </div>
    </div>
  </div>

<% end %>

</div>
</div>

app/views/directions/new.html.erb
<h1><%= t('directions.direction_new') %></h1>

<%= form_for :direction, url: directions_path do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.label :thumbnail %><br />
    <%= f.text_area :thumbnail %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/directions/show.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><%= @direction.title %></h3>
  		</div>
  		<div class="panel-body">

  			<%= render :file => "public/directions_html/#{@direction.content}" %>
			
		</div>	
	</div>
</div>
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Примеры внедрения</h3>
  		</div>
  		<div class="panel-body">

  			<% @direction.examples.each do |example| %>
	<p>
	<%= link_to "#{example.title}".html_safe,example.content %>	
	</p>
<% end %>
			
		</div>	
	</div>
</div>


<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Добавить пример внедрения</h3>
  		</div>
  		<div class="panel-body">

  			<%= form_for([@direction, @direction.examples.build]) do |f| %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :content %><br />
		<%= f.text_area :content %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	<% end %>
			
		</div>	
	</div>
</div>

app/views/events/new.html.erb
<h1><%= t('events.event_new') %></h1>

<%= form_for :event, url: events_path do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.label :date %><br />
    <%= f.text_area :date %>
  </p>
  <p>
    <%= f.label :thumbnail %><br />
    <%= f.text_area :thumbnail %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/events/show.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><%= @event.date %> <%= @event.title %></h3>
  		</div>
  		<div class="panel-body">

  			<%= render :file => "public/events_html/#{@event.content}" %>
			
		</div>	
	</div>
</div>

app/views/home/index.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
    		<h3 class="panel-title">Новинки продукции</h3>
  		</div>
		
		<div class="panel-body">

			<div style="margin-top: 20px; margin-bottom: 20px;">
			<div id="Carousel" class="carousel slide" data-interval="5000" data-ride="carousel" style="margin-top: 20px;">
				
			<div class="carousel-inner" role="listbox">

  			<% @products.each_with_index do |product, n| %>
     			<div class="item <%= n==0 ? ' active' : '' %>" style="background: #ffffff; height: 300px !important;">
   				<table class="carousel-table">
       			<tr><td class="carousel-td"><%= link_to "#{image_tag(product.thumbnail, :alt => "", :class => "carousel-img")}".html_safe,product_path(product)  %>
    			</td><td class="carousel-td">
        			<h2><%= link_to "#{product.title}".html_safe,product_path(product) %></h2>
      							<%= product.name %>
      							
      							<ul>
      								<% features = product.feature.split(';') %>
      								<% features.each do |item|%>
      									<li><%= item.strip.capitalize %></li>
      								<% end %>
      							</ul>
     			</td></tr>
    			</table>
     			</div>
  			<% end %>
	
  		</div>
		<!-- Carousel nav -->
  		<a class="carousel-control left" href="#Carousel" data-slide="prev">
    	<span class="glyphicon glyphicon-chevron-left"></span></a>
  		<a class="carousel-control right" href="#Carousel" data-slide="next">
    	<span class="glyphicon glyphicon-chevron-right"></span></a>
    	</div>
    	</div>
  </div>
  </div>
  </div>

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
    		<h3 class="panel-title">Области применения</h3>
  		</div>
		
		<div class="panel-body">
			<div class="row">

				<% @directions.each do |direction| %>

  					<div class="col-sm-6 col-md-4">
   						<div class="thumbnail">
      						<%= link_to "#{image_tag(direction.thumbnail, :alt => "", :class => "img-radius")}".html_safe,direction_path(direction) %>
      						<div class="caption">
      							<p class="thumbnails-text"><%= direction.title %></p>
      						</div>
    					</div>
  					</div>

  				<% end %>
			</div>
		</div>  
	</div>
</div>

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">События компании</h3>
  		</div>
  		<div class="panel-body">

  			<% @events.each do |event| %>

				<div class="media">
 					<div class="media-left media-top">
    					
    					<%= link_to "#{image_tag(event.thumbnail, :alt => "", :class => "media-object")}".html_safe, event_path(event)  %>
    					      					
  					</div>

  					<div class="media-body">
  						<h4><%= event.date %></h4>
  						<p></p>
    					<h5 class="media-heading"><%= event.title %></h5>
					</div>
				</div>

			<% end %>
			
		</div>	
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>НПП "Мера"</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="http://nppmera.ru/favicon.ico">
  </head>

  <body>
  <div class="container">
	<div class="col-sm-12 col-md-12">
		<div class="row">
			<%= image_tag "/images/logos/logomera.png" %>
			<nav class="navbar navbar-default">
  				    
   				<ul class="nav navbar-nav">
   				<%= nav_link 'Главная', home_index_path %>
				<%= nav_link 'Продукция и услуги', products_path %>
  				<%= nav_link 'Примеры внедрения', directions_path %>
  				<%= nav_link 'Техническая поддержка', support_path %>
  				<%= nav_link 'О предприятии', about_path %>
  				<%= nav_link 'Документация', docs_path %>
  				<%= nav_link 'Контакты', contacts_path %>
  				</ul>

  			</nav>
 		</div>
 	</div>
</div>
	
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="container">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#about" aria-controls="about" role="tab" data-toggle="tab">О предприятии</a></li>
    <li role="presentation"><a href="#history" aria-controls="history" role="tab" data-toggle="tab">История создания</a></li>
    <li role="presentation"><a href="#serts" aria-controls="serts" role="tab" data-toggle="tab">Сертификаты и лицензии</a></li>
    <li role="presentation"><a href="#partners" aria-controls="partners" role="tab" data-toggle="tab">Заказчики и партнеры</a></li>
    <li role="presentation"><a href="#hunt" aria-controls="hunt" role="tab" data-toggle="tab">Вакансии</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="about"><%= render :file => "public/about/about_company.html" %></div>
    <div role="tabpanel" class="tab-pane fade" id="history"><%= render :file => "public/about/history.html" %></div>
    <div role="tabpanel" class="tab-pane fade" id="serts"><%= render :file => "public/about/serts.html" %></div>
    <div role="tabpanel" class="tab-pane fade" id="partners"><%= render :file => "public/about/partners.html" %></div>
    <div role="tabpanel" class="tab-pane fade" id="hunt"><%= render :file => "public/about/hunt.html" %></div>
  </div>

</div>

 

app/views/pages/contacts.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Контактная информация</h3>
  		</div>
  		<div class="panel-body">

  		<p>Телефон: (495) 783-71-59 (многоканальный)</p>
		<p>Факс: (495) 745-98-93 (факс-автомат)</p>
		<p>E-mail: info@nppmera.ru</p>
			
		</div>	
	</div>
</div>

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">По вопросам технической поддержки</h3>
  		</div>
  		<div class="panel-body">

  		<p>Милосердов Дмитрий Валентинович</p>
		<p>тел: (903)-714-87-84</p>
   		<p>e-mail: miloserdov@nppmera.ru</p>	
			
		</div>	
	</div>
</div>

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">По вопросам стоимости продукции и согласования договоров</h3>
  		</div>
  		<div class="panel-body">

  		<p>Cёмин Антон Анатольевич</p>
		<p>тел: (926)-128-80-93</p>
   		<p>e-mail: a.semin@nppmera.ru</p>	
			
		</div>	
	</div>
</div>

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Адрес</h3>
  		</div>
  		<div class="panel-body">
  		<p>41002, Россия, Московская область, г. Мытищи,
ул. Колпакова, д. 2, корпус № 13 (территория технопарка "Новое Время"), 3 этаж</p>
		<p>
  		<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A4d9a87f1516dd1f5c7746b73ce056713e61fa5ed7fe29c5a75fad09cea338856&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>	</p>
			
		</div>	
	</div>
</div>


 <div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Реквизиты</h3>
  		</div>
  		<div class="panel-body">
  		<p>Наименование предприятия: ООО «НПП «МЕРА»</p>
		<p>ИНН: 5029023560</p>
		<p>КПП: 502901001</p>
		<p>ОГРН: 1025003532091</p>
		<p>ОКПО: 23527974</p>
			
		</div>	
	</div>
</div>

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Для расчётов</h3>
  		</div>
  		<div class="panel-body">
  		<p>Р/с: 40702810840170100602 в ОАО «Сбербанк России» г. Москва</p>
		<p>К/с: 30101810400000000225</p>
		<p>БИК: 044525225</p>
			
		</div>	
	</div>
</div>
  



 

app/views/pages/support.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Техническая поддержка</h3>
  		</div>
  		<div class="panel-body">

  			<%= render :file => "public/support/support.html" %>
			
		</div>	
	</div>
</div>

app/views/products/index.html.erb
<div class="container">
<div class="row">
	<div class="clearfix visible-xs-block"></div>
  		<div class="col-xs-12 col-sm-6 col-md-8">.col-xs-12 .col-sm-6 .col-md-8</div>
  		<div class="col-xs-12 col-sm-6 col-md-4">.col-xs-6 .col-md-4</div>
	</div>
</div>

<h1>Продукция!</h1>
</div>

app/views/products/new.html.erb
<h1><%= t('products.product_new') %></h1>

<%= form_for :product, url: products_path do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>

  
  <p>
    <%= f.label :thumbnail %><br />
    <%= f.text_area :thumbnail %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>